--- 
abstract: Automatically Follow Links Within Responses
author: 
  - Copyright (c) 2007 Daisuke Maki <daisuke@endeworks.jp>
distribution_type: module
generated_by: Module::Install version 0.68
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: GunghoX-FollowLinks
no_index: 
  directory: 
    - inc
    - t
requires: 
  Gungho: 0.09003
  HTML::Parser: 0
  HTML::Tagset: 0
  Sub::Exporter: 0
  URI::Match: 0
tests: t/*.t t/*/*/*.t
version: 0.00001
